[package]
name = "nusamai-gpkg"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio"] }
flatgeom = "0.0"
thiserror = "1.0.69"
url = "2.5.4"
indexmap = "2.7.0"

[dev-dependencies]
tokio = { version = "1.41", features = ["full"] }
