[package]
name = "nusamai-kml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kml = "0.11.0"
flatgeom = "0.0"
