[package]
name = "nusamai-plateau"
version.workspace = true
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
quick-xml = "0.37.1"
serde = { version = "1.0.215", features = ["derive", "rc"], optional = true }
nusamai-citygml = { path = "../nusamai-citygml", features = ["serde"]}
flatgeom = "0.0"
chrono = { version = "0.4.38", features = ["serde"], default-features = false }
url = "2.5.4"
stretto = "0.8.4"
hashbrown = { version = "0.15.2", features = ["serde"] }
indexmap = "2.7.0"
log = "0.4.22"

[dev-dependencies]
zstd = { version = "0.13.2", features = ["zdict_builder"] }
bincode = { version = "2.0.0-rc.3", default-features = false, features = ["std", "serde"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
lz4_flex = "0.11.3"
serde_json = "1.0.133"
