[package]
name = "nusamai-atlas"
edition = "2021"

[dependencies]
iimage = { version = "0.25.1", default-features = false, features = ["rayon", "tiff", "jpeg", "webp", "png"] }
thiserror = "1.0.61"
hashbrown = "0.14.5"
stretto = "0.8.4"

[dev-dependencies]
tempfile = "3.10.1"
