[package]
name = "nusamai-voxelize"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.27"
hashbrown = "0.14"

[dev-dependencies]
nusamai-geometry = { path = "../nusamai-geometry" }
earcut = "0.4"
byteorder = "1.5"
serde_json = "1.0"
indexmap = "2.2"
