[package]
name = "nusamai-geometry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
geo-types = "0.7.11"
geojson = "0.24.1"
